version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: "docker"
  directory: "/src/AV.AvA.BlazorWasmClient/"
  schedule:
    interval: "daily"
- package-ecosystem: "docker"
  directory: "/src/AV.AvA.StorageBackend/"
  schedule:
    interval: "daily"
