# See https://stackoverflow.com/a/48243640/1200847

version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./src/AV.AvA.StorageBackend/Dockerfile
  wasm:
    build:
      context: .
      dockerfile: ./src/AV.AvA.BlazorWasmClient/Dockerfile
  backup-tool:
    build:
      context: .
      dockerfile: ./src/AV.AvA.BackupTool/Dockerfile
