# See https://stackoverflow.com/a/48243640/1200847

version: '3'
services:
  wasm:
    # will build ./src/AV.AvA.BlazorWasmClient/Dockerfile
    build:
      context: .
      dockerfile: ./src/AV.AvA.BlazorWasmClient/Dockerfile
