name: CI Build

on:
  push:
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  wasm:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.BlazorWasmClient/Dockerfile
      container-name-suffix: wasm
      push: false
      # no AOT here
  backend:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.StorageBackend/Dockerfile
      container-name-suffix: storagebackend
      push: false
  backuptool:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.BackupTool/Dockerfile
      container-name-suffix: backuptool
      push: false
