name: CI Build

on:
  push:
    paths-ignore:
      - '**.md'

permissions:
  contents: read
  packages: write

jobs:
  wasm:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.BlazorWasmClient/Dockerfile
      container-name-suffix: wasm
      push: false
      # no AOT here
  backend:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.StorageBackend/Dockerfile
      container-name-suffix: storagebackend
      push: false
  backuptool:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.BackupTool/Dockerfile
      container-name-suffix: backuptool
      push: false
  apply-prerelease-container-retention-policy:
    runs-on: ubuntu-latest
    steps:
    - uses: snok/container-retention-policy@v1
      with:
        image-names: ava-wasm, ava-storagebackend, ava-backuptool
        cut-off: Four hours ago UTC
        timestamp-to-use: updated_at
        account-type: org
        org-name: akademischerverein
        keep-at-least: 2
        skip-tags: latest
        filter-tags: '*-alpha*, *-beta*'
        # this fails because a PAT would be strictly needed here
        # the permission packages:delete is just available for PATs
        # see https://github.com/snok/container-retention-policy#token
        token: ${{ secrets.GITHUB_TOKEN }}
