name: Docker Release Push

on:
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  wasm:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.BlazorWasmClient/Dockerfile
      container-name-suffix: wasm
      push: true
      build-args: |
        AOT=true
  backend:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.StorageBackend/Dockerfile
      container-name-suffix: storagebackend
      push: true
  backuptool:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.BackupTool/Dockerfile
      container-name-suffix: backuptool
      push: true
