name: Docker Compose Build CI

on:
  push

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: dotnet/nbgv@v0.4.0
      id: nbgv
    - name: Build the Docker image
      run: docker-compose build
