name: Docker Build and Push

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: dotnet/nbgv@v0.4.0
      id: nbgv
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Storage Backend
    - name: Extract metadata (tags, labels) for backend
      id: meta1
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-storagebackend
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
    - name: Build and push backend image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/AV.AvA.StorageBackend/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ steps.meta1.outputs.tags }}
        labels: ${{ steps.meta1.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    # WASM
    - name: Extract metadata (tags, labels) for wasm
      id: meta2
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-wasm
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
    - name: Build and push wasm image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/AV.AvA.BlazorWasmClient/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ${{ steps.meta2.outputs.tags }}
        labels: ${{ steps.meta2.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

