name: Release with Docker Push

on:
  workflow_call:
    inputs:
      build-ref:
        required: false
        type: string
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  wasm:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.BlazorWasmClient/Dockerfile
      container-name-suffix: wasm
      push: true
      build-ref: ${{ inputs.build-ref }}
      build-args: |
        AOT=true
  backend:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.StorageBackend/Dockerfile
      container-name-suffix: storagebackend
      push: true
      build-ref: ${{ inputs.build-ref }}
  backuptool:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./src/AV.AvA.BackupTool/Dockerfile
      container-name-suffix: backuptool
      push: true
      build-ref: ${{ inputs.build-ref }}
